#define MICROPY_HW_BOARD_NAME "nomascus//pad"
#define MICROPY_HW_MCU_NAME "rp2040"

#define CIRCUITPY_REPL_LOGO 0
//#define MICROPY_EMIT_THUMB (1)

#define DEFAULT_I2C_BUS_SCL (&pin_GPIO5)
#define DEFAULT_I2C_BUS_SDA (&pin_GPIO4)